spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: system
    password: SYSTEM
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

# ===============================
# GENERIC DB SQL CONFIG
# ===============================
db:
  sql:
    insert:
      transaction: |
        INSERT INTO SYSTEM.SEND_TRANSACTIONS (
          ${transaction.columns}
        ) VALUES (
          ${transaction.params}
        )

      transactionDetail: |
        INSERT INTO SYSTEM.SEND_TRAN_DTL (
          ${transactionDetail.columns}
        ) VALUES (
          ${transactionDetail.params}
        )

      transactionAddress: |
        INSERT INTO SYSTEM.SEND_TRAN_ADDR_DTL (
          ${transactionAddress.columns}
        ) VALUES (
          ${transactionAddress.params}
        )

      recipient: |
        INSERT INTO SYSTEM.SEND_RECIP_DTL (
          ${recipient.columns}
        ) VALUES (
          ${recipient.params}
        )

# ===============================
# COLUMN + PARAM MAPPINGS
# ===============================
transaction:
  columns: >
    TRAN_ID,
    TRAN_INIT_ID,
    ORIG_INST_ID,
    ORIG_INST_NAM,
    TRANFR_ACPT_NAM,
    TRANFR_ACPT_ID,
    TRAN_CRTE_DT,
    TRAN_TYPE,
    CUST_REF_NUM,
    CUR_STAT,
    ORIG_STAT,
    USE_CASE,
    MSG_TYPE,
    REF_ID,
    SW_SER_NUM,
    BNKNT_REF_NUM,
    SEND_ACCT,
    RECIP_ACCT,
    TRAN_AMT,
    TRAN_CURR,
    ERR_CD,
    FUND_AVAIL,
    CORLTN_ID,
    CRTE_TS,
    CRTE_USER_NAM,
    UPDT_TS,
    UPDT_USER_NAM,
    RPLCTN_UPDT_TS,
    NTWRK_CD,
    NTWRK_RESP_CD,
    TRAN_INIT_NAM,
    NAM_STAT,
    CVC_STAT,
    CVC_RESP_CD,
    ACCT_NUM,
    ACCT_TYPE,
    ACCT_HOLD_NAM,
    ERR_CD_DESC,
    NON_FIN_TXN,
    NTWRK_RESP_CD_DESC

  params: >
    :tranId,
    :tranInitId,
    :origInstId,
    :origInstNam,
    :tranfrAcptNam,
    :tranfrAcptId,
    :tranCrteDt,
    :tranType,
    :custRefNum,
    :curStat,
    :origStat,
    :useCase,
    :msgType,
    :refId,
    :swSerNum,
    :bnkntRefNum,
    :sendAcct,
    :recipAcct,
    :tranAmt,
    :tranCurr,
    :errCd,
    :fundAvail,
    :corltnId,
    :crteTs,
    :crteUserNam,
    :updtTs,
    :updtUserNam,
    :rplctnUpdtTs,
    :ntwrkCd,
    :ntwrkRespCd,
    :tranInitNam,
    :namStat,
    :cvcStat,
    :cvcRespCd,
    :acctNum,
    :acctType,
    :acctHoldNam,
    :errCdDesc,
    :nonFinTxn,
    :ntwrkRespCdDesc



transactionDetail:
  columns: >
    TRAN_ID,
    PAYMT_REF,
    UNQ_TRAN_REF,
    ACQ_CNTRY_NAM,
    ACQ_ICA,
    FUND_SRC,
    ICHG_RATE_DSGN,
    MERCH_CAT_CD,
    PAYMT_TYPE,
    POINT_SERV_INTRCTN,
    TRAN_PRPS,
    TRAN_SETL_AMT,
    BNC_GTWAY_RQST,
    BNC_GTWAY_RESP,
    ORIG_RQST_PYLD,
    ORIG_RESP_PYLD,
    TRANFR_ACPT_ID,
    TRANFR_ACPT_NAM,
    MC_ASSGN_MERCH,
    PAYMT_FACILTR_ID,
    SUB_MERCH_ID,
    TRANFR_TRML_ID,
    TRANFR_ACPT_ST_LINE1,
    TRANFR_ACPT_ST_LINE2,
    TRANFR_ACPT_CITY,
    TRANFR_ACPT_ST,
    TRANFR_ACPT_CNTRY_NAM,
    TRANFR_ACPT_POST_CD,
    CRTE_TS,
    CRTE_USER_NAM,
    UPDT_TS,
    UPDT_USER_NAM,
    EVENT_ID,
    EVENT_TS,
    EVENT_CORLTN_ID,
    MSG_VERSION,
    TRAN_CRTE_DT,
    RPLCTN_UPDT_TS,
    TRAN_TYPE_IND_CD,
    REGULATED_RATE_TYPE_CD,
    CVC_RESP_DESC,
    PROC_ID,
    ACQ_IDEN_CD,
    TRANFR_ACPT_MPG_ID,
    TRANFR_ACPT_MERCH_VALUE,
    REMARKS

  params: >
    :tranId,
    :paymtRef,
    :unqTranRef,
    :acqCntryNam,
    :acqIca,
    :fundSrc,
    :ichgRateDsgn,
    :merchCatCd,
    :paymtType,
    :pointServIntrctn,
    :tranPrps,
    :tranSetlAmt,
    :bncGtwayRqst,
    :bncGtwayResp,
    :origRqstPyld,
    :origRespPyld,
    :tranfrAcptId,
    :tranfrAcptNam,
    :mcAssgnMerch,
    :paymtFaciltrId,
    :subMerchId,
    :tranfrTrmlId,
    :tranfrAcptStLine1,
    :tranfrAcptStLine2,
    :tranfrAcptCity,
    :tranfrAcptSt,
    :tranfrAcptCntryNam,
    :tranfrAcptPostCd,
    :crteTs,
    :crteUserNam,
    :updtTs,
    :updtUserNam,
    :eventId,
    :eventTs,
    :eventCorltnId,
    :msgVersion,
    :tranCrteDt,
    :rplctnUpdtTs,
    :tranTypeIndCd,
    :regulatedRateTypeCd,
    :cvcRespDesc,
    :procId,
    :acqIdenCd,
    :tranfrAcptMpgId,
    :tranfrAcptMerchValue,
    :remarks




transactionAddress:
  columns: >
    ID,
    TRAN_ID,
    ADDR_TYPE,
    ST_LINE1,
    ST_LINE2,
    CITY,
    ST,
    CNTRY_NAM,
    POST_CD,
    ADDR_STAT,
    POST_CD_STAT,
    CRTE_TS,
    UPDT_TS,
    CRTE_USER_NAM,
    UPDT_USER_NAM,
    RPLCTN_UPDT_TS

  params: >
    :addressId,
    :tranId,
    :addrType,
    :stLine1,
    :stLine2,
    :city,
    :st,
    :cntryNam,
    :postCd,
    :addrStat,
    :postCdStat,
    :crteTs,
    :updtTs,
    :crteUserNam,
    :updtUserNam,
    :rplctnUpdtTs



recipient:
  columns: >
    TRAN_ID,
    SEND_FIRST_NAM,
    SEND_MID_NAM,
    SEND_LST_NAM,
    SEND_PHN,
    SEND_EMAIL,
    SEND_DOB,
    SEND_NATL,
    SEND_BIRTH_CNTRY_NAM,
    SEND_ACCT_NUM,
    SEND_ACCT_URI,
    SEND_GOVT_ID_URI,
    SEND_ACCT_NUM_TYPE,
    SEND_CARD_NUM,
    SEND_CARD_EXPIR_DT,
    SEND_ST_LINE1,
    SEND_ST_LINE2,
    SEND_CITY,
    SEND_ST,
    SEND_CNTRY_NAM,
    SEND_POST_CD,
    RECIP_FIRST_NAM,
    RECIP_MID_NAM,
    RECIP_LST_NAM,
    RECIP_PHN,
    RECIP_EMAIL,
    RECIP_DOB,
    RECIP_NATL,
    RECIP_BIRTH_CNTRY_NAM,
    RECIP_ACCT_NUM,
    RECIP_ACCT_URI,
    RECIP_GOVT_ID_URI,
    RECIP_ACCT_NUM_TYPE,
    RECIP_CARD_NUM,
    RECIP_CARD_EXPIR_DT,
    RECIP_ST_LINE1,
    RECIP_ST_LINE2,
    RECIP_CITY,
    RECIP_ST,
    RECIP_CNTRY_NAM,
    RECIP_POST_CD,
    CRTE_TS,
    CRTE_USER_NAM,
    UPDT_TS,
    UPDT_USER_NAM,
    TRAN_CRTE_DT,
    RPLCTN_UPDT_TS

  params: >
    :tranId,
    :sendFirstNam,
    :sendMidNam,
    :sendLstNam,
    :sendPhn,
    :sendEmail,
    :sendDob,
    :sendNatl,
    :sendBirthCntryNam,
    :sendAcctNum,
    :sendAcctUri,
    :sendGovtIdUri,
    :sendAcctNumType,
    :sendCardNum,
    :sendCardExpirDt,
    :sendStLine1,
    :sendStLine2,
    :sendCity,
    :sendSt,
    :sendCntryNam,
    :sendPostCd,
    :recipFirstNam,
    :recipMidNam,
    :recipLstNam,
    :recipPhn,
    :recipEmail,
    :recipDob,
    :recipNatl,
    :recipBirthCntryNam,
    :recipAcctNum,
    :recipAcctUri,
    :recipGovtIdUri,
    :recipAcctNumType,
    :recipCardNum,
    :recipCardExpirDt,
    :recipStLine1,
    :recipStLine2,
    :recipCity,
    :recipSt,
    :recipCntryNam,
    :recipPostCd,
    :crteTs,
    :crteUserNam,
    :updtTs,
    :updtUserNam,
    :tranCrteDt,
    :rplctnUpdtTs
