spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XEPDB1
    username: system
    password: SYSTEM
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

# ===============================
# GENERIC DB SQL CONFIG
# ===============================
db:
  sql:
    insert:
      transaction: |
        INSERT INTO SYSTEM.SEND_TRANSACTIONS (
          ${transaction.columns}
        ) VALUES (
          ${transaction.params}
        )

      transactionDetail: |
        INSERT INTO SYSTEM.SEND_TRAN_DTL (
          ${transactionDetail.columns}
        ) VALUES (
          ${transactionDetail.params}
        )

      transactionAddress: |
        INSERT INTO SYSTEM.SEND_TRAN_ADDR_DTL (
          ${transactionAddress.columns}
        ) VALUES (
          ${transactionAddress.params}
        )

      recipient: |
        INSERT INTO SYSTEM.SEND_RECIP_DTL (
          ${recipient.columns}
        ) VALUES (
          ${recipient.params}
        )

# ===============================
# COLUMN + PARAM MAPPINGS
# ===============================
transaction:
  columns: >
    TRAN_ID,
    TRAN_INIT_ID,
    ORIG_INST_ID,
    ORIG_INST_NAM,
    TRAN_TYPE,
    TRAN_AMT,
    TRAN_CURR,
    CUR_STAT,
    ORIG_STAT,
    USE_CASE,
    MSG_TYPE,
    CUST_REF_NUM,
    CRTE_TS,
    UPDT_TS

  params: >
    :tranId,
    :tranInitId,
    :origInstId,
    :origInstNam,
    :tranType,
    :tranAmt,
    :tranCurr,
    :curStat,
    :origStat,
    :useCase,
    :msgType,
    :custRefNum,
    :crteTs,
    :updtTs



transactionDetail:
  columns: >
    TRAN_ID,
    PAYMT_REF,
    UNQ_TRAN_REF,
    ACQ_ICA,
    FUND_SRC,
    MERCH_CAT_CD,
    TRAN_PRPS,
    TRAN_SETL_AMT,
    REMARKS,
    CRTE_TS

  params: >
    :tranId,
    :paymtRef,
    :unqTranRef,
    :acqIca,
    :fundSrc,
    :merchCatCd,
    :tranPrps,
    :tranSetlAmt,
    :remarks,
    :crteTs



transactionAddress:
  columns: >
    ID,
    TRAN_ID,
    ADDR_TYPE,
    ST_LINE1,
    ST_LINE2,
    CITY,
    ST,
    CNTRY_NAM,
    POST_CD,
    ADDR_STAT,
    POST_CD_STAT,
    CRTE_TS,
    UPDT_TS

  params: >
    :addressId,
    :tranId,
    :addrType,
    :stLine1,
    :stLine2,
    :city,
    :st,
    :cntryNam,
    :postCd,
    :addrStat,
    :postCdStat,
    :crteTs,
    :updtTs



recipient:
  columns: >
    TRAN_ID,
    SEND_FIRST_NAM,
    SEND_MID_NAM,
    SEND_LST_NAM,
    SEND_PHN,
    SEND_EMAIL,
    RECIP_FIRST_NAM,
    RECIP_MID_NAM,
    RECIP_LST_NAM,
    RECIP_PHN,
    RECIP_EMAIL,
    CRTE_TS

  params: >
    :tranId,
    :sendFirstNam,
    :sendMidNam,
    :sendLstNam,
    :sendPhn,
    :sendEmail,
    :recipFirstNam,
    :recipMidNam,
    :recipLstNam,
    :recipPhn,
    :recipEmail,
    :crteTs
